### ISSUE TITLE
Format Subpage | Change Form Template

### ISSUE THREAD

**Issue by DevinJohnston** [compensationServiceTraining/curriculumCreationGuide#41]
Please add the fillable PDF Change Form that you and I created last January(ish?) so we have consistency in use of that, rather than the old LOC document that some folks are still using
[Change Form_v1.pdf](https://github.com/compensationServiceTraining/curriculumCreationGuide/files/7915066/Change.Form_v1.pdf)
.

**Comment by jrvictor** [comment]
My only suggestions are to add "/transcript" to the "slide notes" document category and perhaps instructions to briefly summarize the changes made in the triggers section or an additional section, if appropriate. Summarizing changes made can be helpful to reviewers, especially in situations where changes need to be reverted or older versions need to be restored due to human error or file corruption, etc.

**Comment by kdavisva** [comment]
At this time, my vote is no. As this is the first time I have seen this form, I would like some time to review with our staff. My first comment, is that instead of trigger 1, 2, 3, ect that the triggers be spelled instead of having to bounce back and forth between the form and the CCG.

**Comment by artlessdodger** [comment]
Issue is deferred for Board discussion following objection of a voting member. @cassbg, @lukebelcher please include this issue as a discussion point in the next Board meeting.

**Comment by kdavisva** [comment]
I appreciate the time allowed to canvass 213A/G concerning the Change form document. I have received the following comments/questions from the 213A/G staff regarding the new form.
1.	The old LOC form was a running document that was updated every time a lesson/module was updated. This document was uploaded to the LC. The new Change Form document appears to be for an one-time use. If that is true, will the historical documents be updated to the LC or only stored in the CPTX repository? Or will the new Change Form also be a running document?
2.	Recommend adding a checkmark for “lesson plan.”
3.	The section “Please identify exactly where the changes are located” - it is just an open block. Is there guidance on how to list the changes?
4.	The Triggers need to be spelled out instead of jumping back and forth between the document and the CCG. 
5.	Are there any specific instructions on how this form is to be filled out.

Some had seen the new form as they have worked with 213C/D, however others had not, so they were unsure why 213C/D was using a different form. However, several voiced they liked the new form with some minor updated. 

Any comments/clarification would be appreciated.

**Comment by jrvictor** [comment]
@kdavisva great suggestions! I am in total agreement with you, particularly regarding tracking historical changes somehow. The only thing I question is that to my knowledge we are no longer using "lesson plans" in any of our curricula - this doc has been replaced w/ transcripts (modules/simulations) and instructor slide notes (instructor-led lessons). Someone please correct me if I'm wrong on that.

**Comment by artlessdodger** [comment]
@kdavisva, I think I can clarify some of this —

>1. The old LOC form was a running document that was updated every time a lesson/module was updated. This document was uploaded to the LC. The new Change Form document appears to be for an one-time use. If that is true, will the historical documents be updated to the LC or only stored in the CPTX repository? Or will the new Change Form also be a running document?

Historical published files and their associated course resources, to include the change form, should be placed in the course's Connect folder. 

The only items that should be placed in the cptx_repository are the CPTX files and non-linked media used in creation of the course (e.g., images, audio, etc.).

See the **Format** subpage of the Curriculum Creation Guide (CCG), under the **folders | Connect** and **folders | repository** sections. 

>2. Recommend adding a checkmark for “lesson plan.”

Lesson Plans have been replaced by slide notes and transcript course resources.

See the **Format** subpage of the Curriculum Creation Guide (CCG), under the **templates** section. 

>3. The section “Please identify exactly where the changes are located” - it is just an open block. Is there guidance on how to list the changes?

Form guidance is tentatively planned to be added to the **Create** subpage, within the **step two | create** section. Guidance will include instructions for all fillable form fields.

>4. The Triggers need to be spelled out instead of jumping back and forth between the document and the CCG.

Noted; edits to the form can be made.

>5. Are there any specific instructions on how this form is to be filled out.

See item 3's response.

**Comment by lukebelcher** [comment]
Hello everyone!

The CCG (now CCSOP) already identifies the Change Form as a document to be placed in the Course's Adobe Connect folder (see image below).  

![Screenshot 2022-01-26 062139](https://user-images.githubusercontent.com/77509060/151162096-804d3b6e-fe8a-41fd-a765-cc0ac1deb646.png)

As a matter of fact, I couldn't find a LOC identified anywhere in the CCSOP.  I'm not sure how long the instructions have listed the Change Form (I tried to search through the archives to no avail), but it has been there for a while (my best estimated guess is for roughly a year).  213C/D have been using this form almost since the team was stood up in Nashville and we were updating courses.  

The original request was to add the fillable Change Form (probably the best place to add it would be the Templates section, just above where the Change Form is already mentioned). Obviously, there are some recommendations as to modifications to this form.  From my point of view, this is a separate issue from the original request.  My recommendation is, since the Change Form was already mentioned in the CCSOP and has been in use for quite some time, to go ahead and include it as a template and close this issue out and then move any of the conversation regarding modification of the document a different issue.  This way, the document (which is already in use) can be added for the time being while 213/CC Board discussion can take place as to any upgrades to the document itself.

Thanks!

**Comment by kdavisva** [comment]
After our meeting on 02-10-2022 and talking with the CCG board, I agree with using the new change form template that has been created. I believe that we can now close this issue and upload the change form template to the CCG.

**Comment by artlessdodger** [comment]
Change Form guidance has been added to the create subpage and the format subpage (see commit [ef17d90](https://github.com/compensationServiceTraining/curriculumCreationGuide/commit/ef17d9001d3d4216b7aa9b8aaa3361aae021b9b5))
